package lk.ijse.spicesystem.util;

public enum Routes {
    LOGIN, SIGNUP, CEO, CEODASHBOARD, STOCKMANAGER, STOCKMANAGERDASHBOARD, HR, HRDASHBOARD, FINANCEMANAGER, FINANCEMANAGERDASHBOARD, SALESMEN, SALESMENDASHBOARD,
    ADDSHOPFORM, CUSTOMERDASHBOARD, SEARCHSHOPFORM, UPDATESHOPFORM, DELETESHOPFORM, ADDFINISHEDSTOCK, ADDPRODUCTIONSTOCK, ADDRAWSTOCK,
    ADDSUPPLIER, SEARCHSUPPLIER, DELETESUPPLIER, UPDATESUPPLIER, SUPPLIERDASHBOARD, EMPLOYEEDASHBOARD, ADDEMPLOYEE, SEARCHEMPLOYEE,
    DELETEEMPLOYEE, UPDATEEMPLOYEE, EDITPROFILE, PLACEORDER, SALARYRECCOMEND
}
